-- Better Auth schema for YSD Zero Cloud.
--
-- Generated by `npm run auth:schema`. Do not edit by hand: rerun the script
-- after changing lib/server/auth-options.ts or upgrading better-auth.
-- Tables created: rateLimit
-- Columns added: none
create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);
